### ISSUE TITLE
native-plasma doesn't work

### ISSUE THREAD

**Issue by Whiteseeker** [googlesamples/android-ndk#134] opened 2015-12-10 15:44 UTC
Native-plasma currently doesn't work on devices like samsung galaxy s2, nexus 6, ...

**Comment by ggfan** [comment] 2016-05-04 23:17
closing 
https://github.com/googlesamples/android-ndk/issues/166 ( I opened )  and using this one as a holder to debug

**Comment by Whiteseeker** [comment] 2016-05-05 07:45
We should have merged the code I submitted months ago :P It would be fixed ^^

**Comment by ggfan** [comment] 2016-05-05 15:18
Ok, I did not realize there is a fix on the way and I was there before too :-(.  Let me look through to see what this sample does and go from there.

**Comment by ggfan** [comment] 2016-05-05 17:15
Ok, the problem is that: on my android 5X, the window format is 8888 ( RGBA ), the fill_plasma code is for 565 format ( 16 bit format ). fixable :-) just need to understand the original algorithm.

**Comment by ggfan** [comment] 2016-05-05 18:34
this one https://github.com/googlesamples/android-ndk/pull/190
will fix it:  request the 565 format before drawing on it. There got to be something similar for the same thing inside androidManifest.xml, not found it yet...

**Comment by ggfan** [comment] 2016-05-05 19:26
merged, it should be fixed and the functionality matches the one inside bitmap-plasma
Whiteseeker@, let's process your improvement for this sample inside the pull:
  https://github.com/googlesamples/android-ndk/pull/133

The styles are common to:
   bitmap-plasma
   native-plasma
   native-audio

**Closed by ggfan** 2016-05-05 19:26 UTC
Labels: bug, p1
