### ISSUE TITLE
native-audio sample is buggy

### ISSUE THREAD

**Issue by proppy** [googlesamples/android-ndk#39] opened 2015-07-21 08:14 UTC
it doesn't seems to playback anything and crashes with the following stacktrace when pressing record multiple times in a row.
```
I/DEBUG   (  354): Abort message: '/Users/proppy/android-ndk/native-audio/app/src/main/jni/native-audio-jni.c:741: Java_com_example_nativeaudio_NativeAudio_startRecording: assertion "SL_RESULT_SUCCESS == result" failed'
I/DEBUG   (  354):     r0 00000000  r1 00007ac2  r2 00000006  r3 00000000
I/DEBUG   (  354):     r4 b6fc6e38  r5 00000006  r6 0000000b  r7 0000010c
I/DEBUG   (  354):     r8 12cf15d0  r9 b4827800  sl 00000000  fp 00000000
I/DEBUG   (  354):     ip 00007ac2  sp bea1e1b0  lr b6e433fd  pc b6e666c4  cpsr 600b0010
I/DEBUG   (  354): 
I/DEBUG   (  354): backtrace:
I/DEBUG   (  354):     #00 pc 0003a6c4  /system/lib/libc.so (tgkill+12)
I/DEBUG   (  354):     #01 pc 000173f9  /system/lib/libc.so (pthread_kill+52)
I/DEBUG   (  354):     #02 pc 0001800b  /system/lib/libc.so (raise+10)
I/DEBUG   (  354):     #03 pc 000147cd  /system/lib/libc.so (__libc_android_abort+36)
I/DEBUG   (  354):     #04 pc 00012f7c  /system/lib/libc.so (abort+4)
I/DEBUG   (  354):     #05 pc 00015ae9  /system/lib/libc.so (__libc_fatal+16)
I/DEBUG   (  354):     #06 pc 00014851  /system/lib/libc.so (__assert2+20)
I/DEBUG   (  354):     #07 pc 00002ead  /data/app/com.example.nativeaudio-1/lib/arm/libnative-audio-jni.so (Java_com_example_nativeaudio_NativeAudio_startRecording+188)
I/DEBUG   (  354):     #08 pc 00000f65  /data/dalvik-cache/arm/data@app@com.example.nativeaudio-1@base.apk@classes.dex
W/ActivityManager(  816):   Force finishing activity 1 com.example.nativeaudio/.NativeAudio
I/DEBUG   (  354): 
I/DEBUG   (  354): Tombstone written to: /data/tombstones/tombstone_00
I/BootReceiver(  816): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
E/JavaBinder(  816): !!! FAILED BINDER TRANSACTION !!!
W/ActivityManager(  816): Exception thrown during pause
W/ActivityManager(  816): android.os.TransactionTooLargeException
W/ActivityManager(  816): 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  816): 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  816): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager(  816): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager(  816): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
W/ActivityManager(  816): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
W/ActivityManager(  816): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
W/ActivityManager(  816): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11509)
W/ActivityManager(  816): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11406)
W/ActivityManager(  816): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12090)
W/ActivityManager(  816): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11601)
W/ActivityManager(  816): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
W/InputDispatcher(  816): channel '3ba18171 com.example.nativeaudio/com.example.nativeaudio.NativeAudio (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  816): channel '3ba18171 com.example.nativeaudio/com.example.nativeaudio.NativeAudio (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by ggfan** [comment] 2016-05-03 22:33
reproducing[I think this is due to the fact that it is recording then another recording request coming in again]

**Comment by ggfan** [comment] 2016-05-04 01:01
https://github.com/googlesamples/android-ndk/pull/188 will fix that hang.

**Comment by ggfan** [comment] 2016-05-04 23:13
it is merged, the crash thing should be fixed. playing are serialized

**Closed by ggfan** 2016-05-04 23:13 UTC
Labels: bug, need-repro, p1
