### ISSUE TITLE
Jni with Static Library

### ISSUE THREAD

**Issue by bharatiadkar** [googlesamples/android-ndk#239] opened 2016-06-27 20:31 UTC
Hi,
As per your request I am creating a new issue to create app using third party static lib in a jni based Android Application.
Please add an an example to show how to add a C or Cpp based third party static library to an Android Studio jni project.
I have tried using with Hello-libs example, and it does not work for me.
Please let me know when the example is ready.

Thanks,

**Comment by ggfan** [comment] 2016-06-27 21:03
thanks.  I will get one example here.  for your issue, may you put your directory under your static lib: mainly interested in how many ABI you support there.

for example case:
1) https://github.com/playgameservices/cpp-android-basic-samples/blob/master/samples-android/ButtonClicker/build.gradle
   it is a little overhead heavy in this gradle file, just focus on libgpg.a, ignore others. It might take some efforts to run it since play game need one account on play store etc. But it is live and working example

2) https://github.com/ggfan/android-ndk/tree/gradle-static-lib-showcase, sample endless-tunnel.
    used to solve similar issue here.  It used to be working but you might meet problem when you use ndk-12 since hardfloat is not in compiler anymore [just remove them should work ].

I am very interested in your build.gradle and your local static lib file structure, let me know so we could figure out what the problem is

**Comment by ggfan** [comment] 2016-07-01 23:06
may you help close this one when you get it under control? thanks

**Comment by ggfan** [comment] 2016-07-28 03:43
Now hello-libs is added into master-ndkbuild branch to demo how 3rd party lib is used. Closing this one for now, local static lib could be found in Teapot in three branches too.  feel free to reopen when needed, thanks

**Closed by ggfan** 2016-07-28 03:43 UTC
