### ISSUE TITLE
README should warn that editing gradle properties from Android Studio UI is not supported

### ISSUE THREAD

**Issue by 2bitProgammer** [googlesamples/android-ndk#61] opened 2015-08-20 01:23 UTC
This is extremely similar to closed issue #47 , though they didn't say what the fix was.  I just did a fresh download of Android Studio 1.3 and downloaded the NDK bundle via AndroidStudio.  I have the following installed (amoungst others):

* Android Support Library 23
* Android Support Repository 17
* Ndk Bundle 1
* Android SDK Tools 24.3.4
* Android SDK Platform-tools 23
* Android SDK Build-tools 23
* Android SDK Build-tools 22.0.1
* SDK Platform 23 1 
* Google APIs 23 1
* SDK Platform 22 2 
* Google APIs 21 1

I cloned the samples repo from github and tried to build it.  I get the following error: 

```
Error:(16, 0) Gradle DSL method not found: 'android()'
Possible causes:<ul><li>The project 'Teapot' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
```

My build.gradle:
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle-experimental:0.2.0'
    }
}
allprojects {
    repositories {
        jcenter()
    }
}

android {
    compileSdkVersion 22
    buildToolsVersion '22.0.1'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
dependencies {
}
```

My gradle-wrapper.properties
``` gradle
#Wed Apr 10 15:27:10 PDT 2013
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.5-bin.zip
```

**Comment by ggfan** [comment] 2015-08-20 05:55
it seems you are still using the previous version of gradle plugin; the new one uses "model". May you check you check whether your local downloaded .../teapot/build.gradle looks like this one:
https://github.com/googlesamples/android-ndk/blob/master/Teapot/build.gradle

and your module build.gradle at .../teapot/app/build.gradle looks like this one:
https://github.com/googlesamples/android-ndk/blob/master/Teapot/app/build.gradle
note: if you see  
   apply plugin: 'com.android.model.application'
that would be good. your pasted code does not seem to be same as the code in github.  please check it out and update your finding, we could continue to investigate

**Comment by JoeBruner** [comment] 2015-08-20 12:13
Hmmm, so apparently those changes happened when I went to Open Model Settings > Properties and set any of the properties.  I had initially changed the properties because I only downloaded buildtools 23 and it was looking for 22.0.1.  I downloaded 22.0.1 and then went in the dialog to change it and it must have added those fields.  Now I'm getting the error about bad magic numbers (issue #58) which I was able to fix using the posted solution.  Note, however, that if I use the F4 Properties dialog to set the versions to 1.7, it does so by adding the code block
``` gradle
android {
    compileSdkVersion 22
    buildToolsVersion '22.0.1'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
```

**Comment by ggfan** [comment] 2015-08-20 15:45
Here is my steps for the samples:
1) download and install android studio review version at http://tools.android.com/download
2) get sample code:   git clone https://github.com/googlesamples/android-ndk.git
3) start up android studio,  open existing project, navigate into the Teapot directory and open it; you might be asked to find the location of your sdk and ndk, config them; Android studio will automatically sync your project and complains about your NDK location, you would click on the error message and set it up
4) Sync the project, again you will configure the ndk location if you were not asked in above steps [ or you could put into your local.properties]
5) build the project and download to your device to run via USB [maybe emulator too, but openGL thing might give your better experience when you are on real device ]

during the process, normally I do not need to change anything else. 
May you check against with your procedure? Maybe you are on Windows, the procedure should be similar if not the same.  Please update your findings so we could continue to find out what is wrong

**Comment by ggfan** [comment] 2015-08-20 15:48
Oh, since you are using the Java 8, you need to add the 
    compileOptions.with {
        sourceCompatibility=JavaVersion.VERSION_1_7
        targetCompatibility=JavaVersion.VERSION_1_7
    }
  in the module build.gradle inside android section, and android section is inside the model section.

**Comment by proppy** [comment] 2015-08-20 18:19
Happy to continue to discussion in #43. We should update the `README.md` with instruction on how to set JDK 1.7 and/or add the proper `build.gradle` workaround.

**Comment by proppy** [comment] 2015-08-20 19:01
reopening this, since we need to clear up why Android Studio made incompatible change to your app `build.gradle` and escalate to b.android.com.

Sorry for the noise.

**Comment by proppy** [comment] 2015-08-21 00:22
Can you try out with "Android Studio 1.3.1", I don't see the `Open Module Settings` item anymore when I right click on the app module gradle file.

**Comment by proppy** [comment] 2015-08-21 00:25
OK, managed to reproduce it with `Build / Edit Build Types ... / Properties / Compile SDK Version`.

It will insert:
```
android {
    compileSdkVersion 21
}
dependencies {
}
```
Using the old DSL syntax, we should update the README.md to call this out, and get a bug filed on bug.android.com.

**Comment by proppy** [comment] 2015-08-21 00:28
Updated this issue to track this.

**Comment by proppy** [comment] 2015-08-21 00:36
Filed https://code.google.com/p/android/issues/detail?id=183381

**Comment by ggfan** [comment] 2016-05-05 22:31
created a pull request: 
https://github.com/googlesamples/android-ndk/pull/191

since we have a bug tracking it, and it will not be enabled from a while, I like to close this one for now.  please let me know your thought, thanks

**Comment by ggfan** [comment] 2016-05-07 01:56
closing this w/o a proper fix.  feel free to re-open it.

**Closed by ggfan** 2016-05-07 01:56 UTC
Labels: bug, p1
