### ISSUE TITLE
endless-tunnel crash on start

### ISSUE THREAD

**Issue by ip** [googlesamples/android-ndk#102] opened 2015-09-21 15:21 UTC
```
09-21 18:19:43.903  31183-31183/? W/ContextImpl﹕ Failed to ensure directory: /storage/extSdCard/Android/obb/com.google.example.games.tunnel
09-21 18:19:43.903  31183-31183/? W/ContextImpl﹕ Failed to ensure directory: /storage/extSdCard/Android/data/com.google.example.games.tunnel/files
09-21 18:19:43.913  31183-31183/? W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4177bda0)
09-21 18:19:43.913  31183-31183/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.example.games.tunnel, PID: 31183
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.example.games.tunnel/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.google.example.games.tunnel-1/libgame.so
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5479)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.google.example.games.tunnel-1/libgame.so
            at android.app.NativeActivity.onCreate(NativeActivity.java:183)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5479)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

```

**Comment by ip** [comment] 2015-09-21 16:05
I'm using Android Studio 1.3 and Samsung Galaxy Tab 4 with Android 4.4.2. It crashes with GDB, LLDB and when just manually launched from device.

**Comment by proppy** [comment] 2015-10-02 01:48
Thanks for the report, I filed #108 so that we can detect this kind of crashes in the future.

**Comment by AndrewDevAndroid** [comment] 2015-11-28 08:41
I have the same issue, Unable to load native library: /data/data/com.google.example.games.tunnel/lib/libgame.so (it's without increment build number), "native-activity", and also runs perfectly.

**Comment by ggfan** [comment] 2016-04-27 05:56
may you check if this is still a problem? seems worked for me a couple of times

**Comment by ip** [comment] 2016-04-27 17:10
Since I posted this issue, I changed OS from Windows 10 to Ubuntu 16.04 but this bug persists.
Here is the log: https://gist.github.com/ip/a6e4445c15a60cf4ff98e04f5eb09395

Maybe I import the project incorrectly? Here how I do it:
- In Android Studio at "Welcome to Android Studio" window, I choose "Import project (Eclipse ADT, Gradle, etc.)"
- Select "endless-tunnel" directory
- Tools -> Android -> Sync project with Gradle files
- Select "app-native" run configuration
- Run on device
Please tell if it's correct.

**Comment by ggfan** [comment] 2016-04-27 17:44
thank you for the update! your procedure are same as mine, so let's trust ourselves here and assume they are perfect :-). whatever happens on your end is relating to target, I feel.

I am on 14.04 unbuntu, and got the source code and run on emulator -- Nexus 5, API 23 - x86.  this give me the expected result: build and runs fine. your device is 4.4.2 which supports GL3 ( this apps only needs GL2). Not sure what is going on, wondering if you could try it on the emulator to see at least we get on the same page, then we could root cause more. 

Android version 2.1 preview 1, but I do not think it matters. Make sure you are building for your ABI (got to be armeabi-v7a). 

may you give it a shot on emulator on your linux box?  thank you

**Comment by ip** [comment] 2016-04-28 16:04
My emulator doesn't want to start: https://gist.github.com/ip/ee37c0391fa36df80f5469cc7916f350

**Comment by ggfan** [comment] 2016-05-03 00:05
yes, saw it on kitkat.  will debug more and update accordingly

**Comment by ggfan** [comment] 2016-05-03 06:41
Ok, on my end, adding platformVersion into app/build.gradle fixed the problem:
        ndk {
            platformVersion = 19
            moduleName = 'game'  //this was there before, do not change
            ......
you might change it to a lower version than your system level; mine is 19, if I changed it to 12, still works.  may you kindly try it out and let us know?  thanks

**Comment by ggfan** [comment] 2016-05-03 21:44
this one is merged in:  https://github.com/googlesamples/android-ndk/pull/187
it supposed to fix it, may you kindly try it out?  I am closing this one, but do not hesitate to re-open it if it still crashes.

suppose Teapot/MoreTeapot/EndlessTunnel all be runnable,  with moreTeapot being color corrupted, I will file a bug later for that particular issue

thank you for your patience along the way

**Closed by ggfan** 2016-05-03 21:44 UTC
Labels: bug, need-repro, p1

**Comment by ip** [comment] 2016-05-06 11:27
Now it works fine, thank you very much :smile:

**Comment by ggfan** [comment] 2016-05-06 14:27
great!  thanks for the update.
