### ISSUE TITLE
Teapot example freezes after display sleep

### ISSUE THREAD

**Issue by fierodeval** [googlesamples/android-ndk#508] opened 2018-03-18 22:06 UTC
Hello,

I have this behavior in a device with Android 4.2.2, API 17. With, Settings -> Developer options -> Stay awake = off
When the Teapot application launch, after the defined time of inactivity, the first time that the display switch off (only the first time), if we press the phone button to switch on the screen, the application is freezed.
I noticed that when display switch off, a message APP_CMD_TERM_WINDOW is sent, and then, when the display switch on, a message APP_CMD_INIT_WINDOW is sent. The focus does not change, so APP_CMD_GAINED_FOCUS message is not sent.

The variable Engine::m_bHasFocus is false, for this reason the application does not call DrawFrame() function.

To fix this, I added this line to TeapotNativeActivity.cpp:

        case APP_CMD_INIT_WINDOW:
            // The window is being shown, get it ready.
            if (app->window != NULL) {
                eng->InitDisplay(app);
                eng->m_bHasFocus = true;  // Line added to fix this issue
                eng->DrawFrame();
            }
            break;

What do you think?

best regards!

**Comment by ggfan** [comment] 2018-03-26 23:53
I do not think I could answer your question: how about you create a Pull Request, and then we go from there (it is nice to root cause to where is the problem, and make sure it does not conflict with newer OS )?

**Comment by ggfan** [comment] 2018-07-20 18:22
@fierodeval : checked in your code, thanks!  It should be there as app turns  it off on event APP_CMD_TERM_WINDOW, it should turn it back on with the opposite event. No side effect found on pixel device and simulator case.  Thanks!

**Closed by ggfan** 2018-07-20 18:22 UTC
